title: Help for Ukraine web banner
email: it@biano.com
repository: "BianoCZ/ua-banner"
show_downloads: true

# Build settings
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
